### ISSUE TITLE
Batch size send deadline exceeded

### ISSUE THREAD

**Issue by ldurak** [GoogleCloudPlatform/prometheus-engine#149]
Hi,
I'm using Prometheus v2.28.1-gmp.4-gke.0 in my setup as a self managed deployment. Short time after installation I'm getting OOM's on the shards (I have 7) 

`    State:       Running
      Started:   Wed, 02 Mar 2022 09:31:57 +0100
    Last State:  Terminated
      Reason:    OOMKilled
      Message:   =/etc/prometheus/config_out/prometheus.env.yaml totalDuration=85.711863ms remote_storage=4.89µs web_handler=945ns query_engine=1.624µs scrape=91.364µs scrape_sd=3.64668ms notify=22.2µs notify_sd=1.350992ms rules=72.414134ms gcm_export=8.188µs
ts=2022-03-02T08:28:13.837Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:28:15.053Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:28:17.568Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:29:14.437Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:29:16.555Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:30:01.486Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:30:01.976Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:30:05.280Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."
ts=2022-03-02T08:31:55.236Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=200 err="rpc error: code = Unavailable desc = Deadline expired before operation could complete."`

Is there any params of will be in the nearest future to manage batch size, timeouts etc.?

**Comment by lyanco** [comment]
Can you try raising the CPU limits for the collectors? This really seems like something on the client side. Our collectors do require much more CPU than regular Prometheus in order to create the protobuf that gets sent to the API.

The batch size of 200 is an implementation detail of our API and shouldn't affect anything locally. It essentially just groups samples in batches of 200 to send. It shouldn't cause an OOM.

The timeout for sending a point is 30s, which shouldn't be hit under normal circumstances.

**Comment by fabxc** [comment]
I think this particular error message is actually produced by our backend. But there should indeed be no need to configure the batch size to address such an error.

Was this an intermittent error or does it keep happening?

**Comment by pintohutch** [comment]
Definitely recommend upgrading to at least `gke.gcr.io/prometheus-engine/prometheus:v2.28.1-gmp.5-gke.0` here as we fixed some issues in our export layer.

**Comment by belarminof** [comment]
I see the issue still present in the latest collector image here https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.4.1/manifests/operator.yaml#L207

**Comment by pintohutch** [comment]
@belarminof or @ldurak are you still seeing these error messages with the latest image `gke.gcr.io/prometheus-engine/prometheus:v2.35.0-gmp.2-gke.0`?

**Comment by ImryLevySadan** [comment]
We have the same issue. we have the last image `gke.gcr.io/prometheus-engine/prometheus:v2.35.0-gmp.2-gke.0`

**Comment by pintohutch** [comment]
@ImryLevySadan - thanks for reporting. Is this intermittent? Or is it constantly happening?

And are you getting the exact same error as originally reported above?

**Comment by pintohutch** [comment]
Ok. I'm going to close the issue for now. Please reach out again if the issue re-occurs and we can take a closer look.
